# Generated by Django 5.0.4 on 2024-04-08 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('amount', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('HomeRent', 'Home Rent'), ('Bills', 'Bills'), ('Transportation', 'Transportation'), ('EMI', 'EMI'), ('Food', 'Food'), ('Education', 'Education'), ('Fuel', 'Fuel'), ('Shopping', 'Shopping'), ('Savings', 'Savings'), ('Entertainment', 'Entertainment'), ('Miscellaneous', 'Miscellaneous')], default='Miscellaneous', max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('priority', models.CharField(choices=[('need', 'need'), ('want', 'want')], default='need', max_length=200)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('amount', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('Salary', 'Salary'), ('Interest', 'Interest'), ('Rental', 'Rental'), ('Business', 'Business'), ('Investment', 'Investment'), ('Pension', 'Pension')], default='Salary', max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
